[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  external_node_modules = ["@netlify/blobs"]

# 1) Forzar HTTPS
[[redirects]]
  from = "http://bmoodcoffee.com/*"
  to = "https://bmoodcoffee.com/:splat"
  status = 301
  force = true

# 2) Forzar no-www (o cambia a www si prefieres)
[[redirects]]
  from = "https://www.bmoodcoffee.com/*"
  to = "https://bmoodcoffee.com/:splat"
  status = 301
  force = true

# 3) API (rewrite interno, no redirect)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/cafeteria-en-puebla"
  to = "/"
  status = 301

[[redirects]]
  from = "/cafeteria-de-especialidad-puebla"
  to = "/cafe-de-especialidad-puebla"
  status = 301

[[redirects]]
  from = "/cafeteria-con-cbd-puebla"
  to = "/cbd-en-el-cafe"
  status = 301

[[redirects]]
  from = "/eventos-cafe-puebla"
  to = "/talleres-de-cafe-puebla"
  status = 301

[[redirects]]
  from = "/taller-de-cafe-puebla"
  to = "/talleres-de-cafe-puebla"
  status = 301
