import { MOCK_MATCHES, PHASES } from './data/mockData.js';
import { trackEvent } from './services/analytics.js';
const tabs=document.querySelectorAll('[data-calendar-tab]'),panels=document.querySelectorAll('[data-calendar-panel]'),featured=document.querySelector('#featured-results'),more=document.querySelector('#featured-show-more'),phaseChips=document.querySelector('#phase-chips'),summary=document.querySelector('#matchday-summary'),matchday=document.querySelector('#matchday-results'),matchdayMore=document.querySelector('#matchday-show-more'),groupsGrid=document.querySelector('#groups-grid'),groupResults=document.querySelector('#group-results'),mexico=document.querySelector('#mexico-matches'),venues=document.querySelector('#mexico-venues'),venueResults=document.querySelector('#venue-results'),heroMexico=document.querySelector('#hero-mexico-cta');
let selectedPhase='grupos-j1',selectedGroup='',selectedVenue='',featuredLimit=6,matchdayLimit=8;
trackEvent('calendario_futbolero_view',{source:'calendar_hub'});bind();renderAll();
function bind(){tabs.forEach(t=>t.addEventListener('click',()=>setTab(t.dataset.calendarTab)));heroMexico?.addEventListener('click',()=>setTab('mexico',{scroll:true}));more?.addEventListener('click',()=>{featuredLimit+=6;renderFeatured()});matchdayMore?.addEventListener('click',()=>{matchdayLimit+=8;renderMatchday()});phaseChips?.addEventListener('click',e=>{const id=e.target.closest('[data-phase-chip]')?.dataset.phaseChip;if(!id)return;selectedPhase=id;matchdayLimit=8;renderPhases();renderMatchday();trackEvent('calendario_filtrado',{filter:'phase',value:id})});groupsGrid?.addEventListener('click',e=>{const g=e.target.closest('[data-group-filter]')?.dataset.groupFilter;if(!g)return;selectedGroup=selectedGroup===g?'':g;renderGroups();trackEvent('calendario_filtrado',{filter:'group',value:g})});venues?.addEventListener('click',e=>{const c=e.target.closest('[data-venue-city]')?.dataset.venueCity;if(!c)return;selectedVenue=selectedVenue===c?'':c;renderVenues();trackEvent('calendario_filtrado',{filter:'venue',value:c})})}
function renderAll(){renderFeatured();renderPhases();renderMatchday();renderGroups();renderMexico();renderVenues()}
function setTab(name,o={}){tabs.forEach(t=>{const a=t.dataset.calendarTab===name;t.classList.toggle('is-active',a);t.setAttribute('aria-selected',String(a))});panels.forEach(p=>p.classList.toggle('is-active',p.dataset.calendarPanel===name));if(o.scroll)document.querySelector('#calendario')?.scrollIntoView({behavior:'smooth',block:'start'})}
function renderFeatured(){const mx=getMexico()[0],today=getMatches().filter(m=>status(m)==='Hoy'),up=getMatches().filter(m=>new Date(m.matchDate).getTime()>Date.now()),list=unique([mx,...today,...up]);featured.innerHTML=list.slice(0,featuredLimit).map(card).join('');more.hidden=featuredLimit>=list.length}
function renderPhases(){phaseChips.innerHTML=PHASES.map(p=>{const count=byPhase(p.id).length,st=count?p.status:'por-confirmar',label=p.name.replace('Fase de grupos - ','').replace('Ronda de ','Ronda ');return `<button type="button" class="bm-phase-chip ${p.id===selectedPhase?'is-active':''}" data-phase-chip="${p.id}"><span>${label}</span><small>${labelStatus(st)}</small></button>`}).join('')}
function renderMatchday(){const p=PHASES.find(x=>x.id===selectedPhase)||PHASES[0],list=byPhase(p.id),st=list.length?p.status:'por-confirmar';summary.innerHTML=`<article><span class="bm-status" data-status="${st}">${labelStatus(st)}</span><h4>${p.name}</h4><p>${list.length?`${list.length} partidos cargados`:'Cruces por confirmar.'}</p></article><article><strong>${list.length}</strong><span>partidos disponibles</span></article><article><a class="bm-btn bm-btn-secondary" href="/#quick-order">Pedir café</a></article>`;matchday.innerHTML=list.slice(0,matchdayLimit).map(card).join('')||'<p class="bm-empty">Fase por confirmar. Se actualizará cuando existan cruces definidos.</p>';matchdayMore.hidden=matchdayLimit>=list.length}
function renderGroups(){const groups=buildGroups();groupsGrid.innerHTML=Object.entries(groups).map(([g,teams])=>`<article class="bm-group-card ${selectedGroup===g?'is-active':''}"><h3>Grupo ${g}</h3><ul>${teams.map(t=>`<li><span>${t.flag}</span>${t.name}</li>`).join('')}</ul><button class="bm-btn bm-btn-secondary" type="button" data-group-filter="${g}">${selectedGroup===g?'Ocultar partidos':'Ver partidos'}</button></article>`).join('');groupResults.innerHTML=selectedGroup?`<h4>Partidos del Grupo ${selectedGroup}</h4>`+getMatches().filter(m=>m.group===selectedGroup).map(card).join(''):''}
function renderMexico(){mexico.innerHTML=getMexico().map(card).join('')}
function renderVenues(){const list=['Ciudad de México','Guadalajara','Monterrey'].map(city=>{const matches=getMatches().filter(m=>m.hostCity===city),stadiums=[...new Set(matches.map(m=>m.venue))].join(' / ');return{city,matches,stadiums}});venues.innerHTML=list.map(v=>`<article class="bm-venue-card ${selectedVenue===v.city?'is-active':''}"><span></span><h3>${v.city}</h3><p>${v.stadiums||'Sede por confirmar'}</p><strong>${v.matches.length} partidos cargados</strong><button class="bm-btn bm-btn-secondary" type="button" data-venue-city="${v.city}">${selectedVenue===v.city?'Ocultar partidos':'Ver partidos'}</button></article>`).join('');venueResults.innerHTML=selectedVenue?`<h4>Partidos en ${selectedVenue}</h4>`+getMatches().filter(m=>m.hostCity===selectedVenue).map(card).join(''):''}
function card(m){return `<article class="bm-match-card"><div class="bm-match-meta"><span>Grupo ${m.group}</span><span>${status(m)}</span></div><div class="bm-match-line"><strong>${m.homeFlag||''} ${m.homeTeam}</strong><span>vs</span><strong>${m.awayFlag||''} ${m.awayTeam}</strong></div><p>${fmt(m.matchDate)} · ${m.venue} · ${m.hostCity}</p><a href="/#quick-order">Café para este partido</a></article>`}
function getMatches(){return[...MOCK_MATCHES].sort((a,b)=>new Date(a.matchDate)-new Date(b.matchDate))}function byPhase(id){return getMatches().filter(m=>m.phase===id||m.phaseId===id)}function getMexico(){return getMatches().filter(m=>/México/i.test(`${m.homeTeam} ${m.awayTeam}`))}function buildGroups(){return getMatches().reduce((a,m)=>{a[m.group]||=[];add(a[m.group],m.homeTeam,m.homeFlag);add(a[m.group],m.awayTeam,m.awayFlag);return a},{})}function add(l,n,f){if(!l.some(t=>t.name===n))l.push({name:n,flag:f})}function unique(ms){const s=new Set;return ms.filter(m=>{if(!m||s.has(m.id))return false;s.add(m.id);return true})}function status(m){const d=new Date(m.matchDate).getTime()-Date.now();if(Math.abs(d)<43200000)return'Hoy';return d<0?'Finalizado':'Próximo'}function labelStatus(s){return({abierta:'Disponible',proximamente:'Próximamente',cerrada:'Cerrada','por-confirmar':'Por confirmar'})[s]||s}function fmt(v){return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}
